repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-merge-conflict
    - id: forbid-new-submodules
    - id: mixed-line-ending
    - id: no-commit-to-branch
      args: ['--branch', 'production']
- repo: local
  hooks:
    - id: check-for-unpinned-dependencies
      name: check-for-unpinned-dependencies
      entry: npx check-for-unpinned-dependencies
      pass_filenames: false
      language: node
    - id: eslint
      name: eslint
      entry: npx eslint .
      pass_filenames: false
      language: node
    - id: prettier
      name: prettier
      entry: npx prettier --check '**/*.{ts,js,tsx,jsx,css,html}'
      pass_filenames: false
      language: node
    - id: audit
      name: npm audit
      entry: npm audit --audit-level=critical --production
      pass_filenames: false
      language: node
