name: Github Actions

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:

  run-tests:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: npm audit
        run: npm audit --audit-level=high
      - name: npm install
        run: npm install
      - name: pre-commit
        run: |
          pip install pre-commit
          pre-commit install
          pre-commit run --all-files
      - name: run integration tests
        run:  npm run ci-headless
      - name: Post to slack
        uses: 8398a7/action-slack@v3
        if: ${{ failure() }}
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  push-containers:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v2
      # production deploy
      - uses: amondnet/vercel-action@v19
        # if: ${{ github.event.ref == 'refs/heads/main' && github.event_name == 'push' }}
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
      # non-production deploy
      - uses: amondnet/vercel-action@v19
        if: ${{ github.event.ref != 'refs/heads/main' && github.event_name == 'push' }}
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
      - name: Post to slack
        uses: 8398a7/action-slack@v3
        if: ${{ failure() }}
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
